### ISSUE TITLE
rmlui - Game Crashes

### ISSUE THREAD

**Issue by Booster1212** [Stuyk/altv-athena-issues#16]
### Description of the problem

```typescript
[[1414::53:53:16]16][[1414::53:53:16]16][Warning] Unable to load glyph for character '32' on the font face 'Arial Bold'; error code: 135.
Unable to load glyph for character '32' on the font face 'Arial Bold'; error code: 135.
Unable to load glyph for character '32' on the font face 'Arial Bold'; error code: 135.
[14:53:16]Unable to load glyph for character '33' on the font face 'Arial Bold'; error code: 135.
```

### Reproduction steps

The game will crash if you have the screenText import in your startup.ts

### Expected behaviour

Should work without crashes or disabled in some of the next Athena updates until its fixed.

### Additional context

Can be temporarily fixed by disabling the screenText import in the startup.ts file.

(src/core/client/startup.ts)
```typescript
// rmlui
// import './rmlui/screenText';
```

### Version

3.1.0

**Comment by xLuxy** [comment]
Cannot reproduce with fresh 3.1.0 Athena. Are you using screenText stuff inside your gamemode?
