### ISSUE TITLE
Dealership Camera won't rotate after 2 turns

### ISSUE THREAD

**Issue by xLuxy** [Stuyk/altv-athena-issues#17]
### Description of the problem

When opening the Purchase menu and keep clicking the `Camera` button - it will go around the car only twice and then stop.

### Reproduction steps

- Open the Dealership Buy menu
- Keep clicking the `Camera` button

### Expected behaviour

Camera should keep rotating around the vehicle.

### Version

3.1.0

**Comment by Stuyk** [comment]
Has to do with spam clicking for sure.
