### ISSUE TITLE
Migrate Discord to Plugin

### ISSUE THREAD

**Issue by Stuyk** [Stuyk/altv-athena-issues#22]
### Description of the problem

The current discord implementation is primitive. It should be updated and moved to a plugin. This includes the `allow list`.

### Desired solution for the problem

* Allow list needs to target a specific role
* Discord Bot Token Support
* Use older version of DiscordJS for the time being (needs to be updated after next alt:V Update)
* Allow list should use role lookups as the yes / no for entry into the server.
* Allow list should stop storing allow list status.

### Version

3.2.1+

**Comment by xLuxy** [comment]
PR: https://github.com/Stuyk/altv-athena/pull/152
