### ISSUE TITLE
Do not transpile plugin files which are disabled

### ISSUE THREAD

**Issue by xLuxy** [Stuyk/altv-athena-issues#23]
### Description of the problem

Currently, all plugin files are transpiled - even the ones from disabled plugins.

### Reproduction steps

run `npm run dev` / `yarn dev`

### Expected behaviour

Disabled plugin files should not be transpiled

### Version

3.2.1+

**Comment by Stuyk** [comment]
Pending fix for merge conflicts.

**Comment by xLuxy** [comment]
> Pending fix for merge conflicts.

Done
