### ISSUE TITLE
Markers and Peds are not displayed

### ISSUE THREAD

**Issue by Terra1990** [Stuyk/altv-athena-issues#25]
### Description of the problem

The markers from the dealership are not displayed the stores are present at the pos but the amrker is not

custom peds are also no longer available 

### Reproduction steps

Run version 3.2.1 in prod mode

### Expected behaviour

Markers should be present as in version 3.1.0

### Additional context

-

### Version

3.2.1

**Comment by Stuyk** [comment]
Production Mode:
![](https://i.imgur.com/oD1qnUi.jpeg)

Assumption:
You ran the server wrong and you're not running the streamer service. Please re-read the documentation in the windows section on how to run the server.

**Comment by Terra1990** [comment]
okay we look :) and report

**Comment by Terra1990** [comment]
ok my mistake sorry
