### ISSUE TITLE
Storage states are not updated in real time

### ISSUE THREAD

**Issue by CANAKIL** [Stuyk/altv-athena-issues#48]
### Description of the problem

After a non-owner player opens the storage page of an interior or vehicle, it doesn't matter if the owner locks it, the non-owner player can still put or take items from the storage. Also with vehicles, after a player accesses the storage, the driver can drive away and the player can still interact with it.

### Reproduction steps

(Two players needed for the reproduction.)
* Interior/Vehicle Storage Not Updating In Real Time
1. Create a house
2. Player A buys the house and unlocks it.
3. Player B opens the storage.
4. Player A locks the interior as Player B still is on the storage menu.
5. Now Player B can interact with the storage even if the house is locked.

* Vehicle Storage Can Still Be Accessed Even If The Driver Drives Away
1. Player A buys a vehicle and unlocks it
2. Player B interacts with the vehicle storage.
3. Player A drives away while Player B is still on the storage page.
4. Player B can still interact with the storage even though the vehicle is away.

### Expected behaviour

The page should be closed automatically or a notification should be displayed when Player B tries to get or put an item to the storage.

### Version

3.3.3

**Comment by Stuyk** [comment]
Needs to be verified @CANAKIL, but the way it works now is if the locks are toggled it auto-kicks out anyone in the storage instnace.

**Comment by CANAKIL** [comment]
> Needs to be verified @CANAKIL, but the way it works now is if the locks are toggled it auto-kicks out anyone in the storage instnace.

It kicks you if you lock an interior/vehicle but for vehicles, the UI still stays there if the player drives away.

**Comment by Stuyk** [comment]
@CANAKIL I don't want to waste performance checking if the car drives away. It would require interval checks against vehicle positions and storage is not meant to have any knowledge of other entities.
