### ISSUE TITLE
Vehicle Storage Bug

### ISSUE THREAD

**Issue by DomePlaysHD** [Stuyk/altv-athena-issues#49]
### Description of the problem

If you start a example Job and try to open Vehicle Storage then no Message is displayed and the 
error "TypeError: Cannot read properties of undefined (reading 'behavior')" is displayed in the Console.

### Reproduction steps

1. Start a example Job
2. Try open storage on wheel menu
3.  Look at console

### Expected behaviour

If you try to open storage and the Vehicle has no data it should return false and show the message "has no storage".

### Version

3.3.3

**Comment by xLuxy** [comment]
Could you please share the whole error log @DomePlaysHD?

**Comment by DomePlaysHD** [comment]
TypeError: Cannot read properties of undefined (reading 'behavior')
    at storage (file://altv-athena-private/resources/core/server/systems/vehicle.js:516:58)
