### ISSUE TITLE
Clothing store makes your cash go below zero

### ISSUE THREAD

**Issue by CANAKIL** [Stuyk/altv-athena-issues#50]
### Description of the problem

If reproduction steps are followed, the clothing store makes your cash go below zero.

### Reproduction steps

1. Go to the clothing store with X amount of money.
2. Pick clothes that are all above X$.
3. Press 'Buy All' and 'Buy' after.
4. Press ESC and check your money.

### Expected behaviour

It should keep your money on positive numbers.

### Version

3.4.0

**Comment by Stuyk** [comment]
Pending Test
