### ISSUE TITLE
Console Commands not working on linux

### ISSUE THREAD

**Issue by Dreandor** [Stuyk/altv-athena-issues#52]
### Description of the problem

Any command on console doesn't work

### Reproduction steps

Install Athena Roleplay Script on Linux Server and try /setadmin DISCORDID 4

### Expected behaviour

When the command is executed, one should be admin on the server

### Version

3.3.3

**Comment by DomePlaysHD** [comment]
Did you start the server via a screen (screen -S altv-server), if so try it without. Then it worked for me.

**Comment by Dreandor** [comment]
I'll start with "npm run linux". Otherwise the server don't launch

**Comment by DomePlaysHD** [comment]
I mean if you typed in the console screen -s and then npm run linux.

**Comment by Dreandor** [comment]
Nope. I don't get an error message or something else

**Comment by jonesXYZ** [comment]
Which program you use for ssh?
Which Linux Version?

..provide us with some informations.

**Comment by Dreandor** [comment]
Debian GNU/Linux 11 (bullseye)
Program for ssh: putty and Solar-Putty

**Comment by Shirobaka** [comment]
Have the same issue on linux.

**Comment by DomePlaysHD** [comment]
> Have the same issue on linux.

Do you have the altv server running in a screen?

**Comment by Shirobaka** [comment]
> > Have the same issue on linux.
> 
> Do you have the altv server running in a screen?

No, i use pterodactyl on linux to run the server, start command is npm run linux

**Comment by Stuyk** [comment]
Fixed in `3.4.0`
