### ISSUE TITLE
Linux broken in current 3.5.0?

### ISSUE THREAD

**Issue by deeMace** [Stuyk/altv-athena-issues#56]
### Description of the problem

My Linux-Production-Server doesn't run any more since i pulled the recent changes. 
First: On my prod-machine is no git, so the "prepare"-Step with Husky will always fail.

(I changed the "prepare"-Step to "husky" so we might need to call this one on develop manually in the index.js)

After i was fixing this, i got the next error down in the Additional Context...

### Reproduction steps

do npm run linux on a linux machine without git (For me its inside a Docker-container)

### Expected behaviour

The Server will startup normally

### Additional context

Logs:

athena_1         | > altv-athena@3.5.0 linux
athena_1         | > node ./scripts/runtime/index.js --start
athena_1         |
athena_1         | ===> Updating dependencies for plugins
athena_1         | node:internal/errors:464
athena_1         |     ErrorCaptureStackTrace(err);
athena_1         |     ^
athena_1         |
athena_1         | Error: spawn ps ENOENT
athena_1         |     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
athena_1         |     at onErrorNT (node:internal/child_process:478:16)
athena_1         |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
athena_1         |   errno: -2,
athena_1         |   code: 'ENOENT',
athena_1         |   syscall: 'spawn ps',
athena_1         |   path: 'ps',
athena_1         |   spawnargs: [ 'awwxo', 'pid,comm' ],
athena_1         |   cmd: 'ps awwxo pid,comm',
athena_1         |   stdout: '',
athena_1         |   stderr: ''
athena_1         | }
athena_1         |

### Version

3.5.0

**Comment by xLuxy** [comment]
Hey, as described on Discord you may not have the ps command installed on your Docker image. Try installing ```sudo apt-get -y install procps``` to your Dockerfile. If that still doesn't help we need the Dockerfile to investigate further.
