### ISSUE TITLE
Faction Menu wont open

### ISSUE THREAD

**Issue by STOinteractive** [Stuyk/altv-athena-issues#58]
### Description of the problem

Hey, when i press K like its described in the video 10 monts ago, nothing happens. i already created the faction but nothing shows up. is there maybe a new way to open it?

### Reproduction steps

Press K after creating a faction
Menu doesnt open

### Expected behaviour

opens faction menu

### Version

3.5.0

**Comment by Booster1212** [comment]
This is not an issue, you can access the Faction Menu by typing /fopen as command.
