### ISSUE TITLE
Deliver Icons and Pictures through a Plugin

### ISSUE THREAD

**Issue by jonasesser** [Stuyk/altv-athena-issues#63]
### Description of the problem

Currently, icons still have to be copied to src-webview so that, for example, the icon is displayed in the inventory. The same is for Webviews.

### Desired solution for the problem

Copy icons in pictures from plugin automatically into the src-webview folder on build. Similar logic as is already done for vue files.

### Version

3.5.0

**Comment by dexslab** [comment]
I was trying to figure out a way to handle this and still allow proper debugging via Vite dev server. This is a dilemma that is not easy to solve.

**Comment by Stuyk** [comment]
Partially solved. Images can be copied based on plugin structure. However, still need to address icon copying.

**Comment by Stuyk** [comment]
This is resolved in `v3.7.0` with new pathing options. See #developers channel for more information.
