### ISSUE TITLE
Make Faction commands public

### ISSUE THREAD

**Issue by jonasesser** [Stuyk/altv-athena-issues#64]
### Description of the problem

Currently all faction commands like handleFactionCreate are private. To reuse them for example in a custom webview (Tablet) it would be helpfull to make them public.

### Desired solution for the problem

Example in Class FactionCommands:

**private** static async handleFactionCreate -> static async handleFactionCreate

### Version

3.7.0

**Comment by Dav-Renz** [comment]
You could just use the actual Faction handler provided in the faction plugin and not the command handler.

https://github.com/Stuyk/altv-athena/blob/47158a41d5c85a906ce6372543fd8ca0d416c6ec/src/core/plugins/core-factions/server/src/handler.ts#L68

**Comment by xLuxy** [comment]
What we could also do is to expose a client-sided method.

Basically, to execute commands, you don't need to make commands public since you can execute commands from client-side using ([ref](https://github.com/Stuyk/altv-athena/blob/dc55e2795cbf44f6d0da33b4c09b536838b2f682/src/core/client/views/chat.ts#L162))
```ts
alt.emitServer(View_Events_Chat.Send, 'commandName', ...args);
```

**Comment by jonasesser** [comment]
> You could just use the actual Faction handler provided in the faction plugin and not the command handler.
> 
> https://github.com/Stuyk/altv-athena/blob/47158a41d5c85a906ce6372543fd8ca0d416c6ec/src/core/plugins/core-factions/server/src/handler.ts#L68

Sure but then I need to do the error handling, permission checks, client emits and all the things in the commands again. Just a few lines of duplicate code, but I thought its easier to make them public.
